version: '3.8'
services:
  nicegui-app:
    build:
      context: .
      dockerfile: rokit_app/Dockerfile
    container_name: rokit-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./rokit_app/:/rokit_app/ 
    restart: on-failure
    network_mode: 'host' 