version: '3.8'
services:
  nicegui:
    build:
      context: ..
      dockerfile: rokit_app/Dockerfile
    container_name: nicegui
    ports: 
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    # depends_on: 
    #   - influxdb